version: "3.3"
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - 7000:7000
      - 9042:9042
  setup:
    image: cassandra
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 20 && cqlsh cassandra < /models/cassy_schema.cql" ]
    volumes:
      - ./models:/models
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - 27017:27017
